### ISSUE TITLE
Data Reduction-Baseline Correction Modification

### ISSUE THREAD

**Issue by aschaen** [WiscAr/pychron#10]
Pychron is calculating baselines differently than how we do it. It appears Pynchon defaults to extrapolating to time-zero via linear regression. We just take averages because baselines are measured over a very short time in only one cycle. Our procedure for calculating baselines is:

a) find the mean of the baseline data
b) throw out baseline measurements >n*std_dev (we use 2 sigma)
c) take the mean of the filtered baseline data
d) subtract this mean from measured data

The difference between the two methods is subtle and most apparent in IC2 where there is typically ~50 counts of noise. Please modify how pychron performs the baselines correction to match our method.

**Comment by jirhiker** [comment]
you need to specify fitting your baselines  with an average fit not a linear fit

**Comment by aschaen** [comment]
got it. sorry for not realizing this was possible. ok to close.
