### ISSUE TITLE
Identifier bug-sample duplication

### ISSUE THREAD

**Issue by aschaen** [WiscAr/pychron#14]
Apparently this has been an issue for a while but I am just noticing it now.....generating unique identifiers in Labnumber for samples which _already_ have grain size info duplicates that sample in the DB. The easiest place for you to see what I mean is if you look at our irradiation UW147 level A. I just entered that one sample in there this morning as a test. It came into Labnumber with grain size info (180-250 um), and after generating the ID, the second entry was duplicated (see editor window). You'll also noticed that the grainsize is not listed in the labnumber list, the version in the list appears to not have all the sample prep meta data associated with it.

This is the reason for all of our duplicate entries in the DB and has been happening for weeks apparently.

![capture](https://user-images.githubusercontent.com/40218738/52972908-ef4b5480-3381-11e9-832f-4e4c0b7edbce.JPG)

**Comment by jirhiker** [comment]
ok. I understand the issue but not the cause. Can you send a log.
