### ISSUE TITLE
Interface request-Analysis Pane

### ISSUE THREAD

**Issue by aschaen** [WiscAr/pychron#6]
In the Analyses Pane, it would be extremely useful if the UUID number appears as a column for each analyses in between the RunID and Sample columns

**Comment by aschaen** [comment]
I do not see this change implemented when using any pipeline. 

![capture](https://user-images.githubusercontent.com/40218738/50907491-2460a080-13ed-11e9-8b72-50edce7a981b.PNG)
line

**Comment by jirhiker** [comment]
you need to configure which columns are displayed by right clicking on in the Analyses pane and selected "configure"

**Comment by aschaen** [comment]
got it. can close, thanks.

**Comment by aschaen** [comment]
Actually, one more related request. In the Blank and IC Factor pipelines where references appear in their own box in the Analyses Pane (beneath the unknowns). In this reference box could you also add the UUID as a configure option like you did for the unknowns?

![capture](https://user-images.githubusercontent.com/40218738/50917134-6d6f1f80-1402-11e9-9a0b-4ffacbbb4650.JPG)
