### ISSUE TITLE
Interface request-Define Equilibration/Iso Evo

### ISSUE THREAD

**Issue by aschaen** [WiscAr/pychron#7]
In the Define Equilibration tab, I really like how all the Ar isotopes for each analyses are displayed at once. This is much more convenient than what is displayed in the Iso Evo pipeline because in this tab you are forced to click on each isotope separately to bring up the plot.  Requests related to this.

1) In the define equilbration tab, the aspect ratios of the plots makes it difficult to view details. This is also because there are 7 plots on top of each other. Can you please change this display to two columns, 3 plots in each column and kick the 36b plot. It would be great if the intercept values were displayed directly on this plot also without have to bring up the RegressionInspector. 

2) Please add the UUID number as a column in the Iso Evo tab in between RunID and Isotope

3) Please add the UUID number as a column in the Define Equil tab in between RunID and Equil Times

**Comment by aschaen** [comment]
1.  nothing changed/modified
2.  looks good
3.  looks good

**Comment by jirhiker** [comment]
1. you need to configure how many columns you want in the Display tab of the DefineEquilibration Options

**Comment by aschaen** [comment]
ok didn't realize. changing the column selection to anything other than 1 prevents the plots from displaying.

**Comment by aschaen** [comment]
all of these initial changes have been made and appear to work well. 1 additional request on the define equil. interface:

when using the new display equil. option to set the number of columns to anything n>1...the resultant plots that are produced in each column have their axes on top of one another (pic, yellow highlight). This makes it difficult to use the drag and fit tools for each plot. Can you add a small space in between these plots to make that easier? This space appears on the default n=1 column display, but anything else the plots overlap. 

![capture](https://user-images.githubusercontent.com/40218738/53751332-aa3f1c00-3e71-11e9-8407-66d64dd597b7.JPG)

**Comment by aschaen** [comment]
looks good! ok to close
