### ISSUE TITLE
Interface request-IC factor display

### ISSUE THREAD

**Issue by aschaen** [WiscAr/pychron#8]
In IC factor pipeline tab, please change the Y axis display to the isotope ratios 39/40, 39/36, 38/26 vs. the detectors ratios.

**Comment by jirhiker** [comment]
ic factors are between detectors not isotopes so for now im going to leave it as is.

**Comment by aschaen** [comment]
I see your point, so keep the axes as is but we need to show the ratios somewhere on these plots for user clarity. How about putting the isotope ratios inside the plots in the top right or left corners?

**Comment by aschaen** [comment]
thank you. ok to close.
